# [START runtime]
runtime: nodejs
vm: true
api_version: 1
module: default
# [END runtime]

# [START resources]
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
# [END resources]

# [START scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
# [END scaling]

env_variables:
  NODE_ENV: production
  PORT: 80
  MONGOHQ_URL: mongodb://mongo-db-8s6m/firefly
  DOMAIN: gdgx-cloud.appspot.com

network:
  name: gdg-x
  instance_tag: web

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
